name: 功能建议
description: 想要新功能或改进
labels: [enhancement]
body:
  - type: textarea
    id: need
    attributes:
      label: 想解决什么
    validations:
      required: true
  - type: textarea
    id: idea
    attributes:
      label: 设想的做法